### ISSUE TITLE
Better request/response introspection

### ISSUE THREAD

**Issue by mjaquilina** [pullingshots/Shipment#29]
Currently, some debugging is possible by virtue of enabling SOAP::WSDL's verbose output and uncommenting "warn $request" in various places in the Shipment modules. But it'd be nice to have more programmatic access to the raw request and response data. This is useful for storing and having access to log data in case it needs to be reviewed with the shipper.

**Comment by pullingshots** [comment]
Introspection is now enabled for Shipment::FedEx by setting the debug attribute or the SHIPMENT_DEBUG environment variable. It will now "warn" both the Request and Response raw XML when debug is set higher than 1.

Added in commit 7b4e39d
