### ISSUE TITLE
USPS Support

### ISSUE THREAD

**Issue by hexfusion** [pullingshots/Shipment#31]
I have an interest in adding direct USPS support.  Are you open to this?

**Comment by mjaquilina** [comment]
I'm not the maintainer of Shipment, but I've found that @pullingshots is very open to pull requests.

A USPS interface is definitely something I'd love to see in Shipment. At present, I'm using a homebrew module that dispatches to Shipment and Business::OnlineShipping::USPS depending on the vendor, so adding USPS support to Shipment is an idea I've thrown around a few times.

**Comment by pullingshots** [comment]
I may be tackling this soon along with Canada Post. Please send any code you have via a pull request. Thanks!
