### ISSUE TITLE
printer_type isa Str but should be PrinterOptions?

### ISSUE THREAD

**Issue by SysPete** [pullingshots/Shipment#33]
enum PrinterOptions is defined in Shipment::Base and also overridden in Shipment::UPS but the type for printer_type attribute is 'Str'. I guess either the enum definitions should be removed or printer_type isa should be corrected.

**Comment by pullingshots** [comment]
The enum definitions have been removed from the Base class.

It is up to the extended classes to enforce type constraints on this.
