### ISSUE TITLE
Add support for basic FedEx tracking

### ISSUE THREAD

**Issue by pullingshots** [pullingshots/Shipment#40]

**Comment by pullingshots** [comment]
2 hours

- research FedEx tracking API, developer documentation
- add tracking wsdl files

**Comment by pullingshots** [comment]
4 hours

- write test script
- add new attributes and classes
- develop track method

**Comment by evanernest** [comment]
Is this going to get into a CPAN release? I had forked this project for another purpose, and had my fork in @INC, thinking it was in sync with CPAN. Then I developed some tracking integration based on the Github version without checking. It works great, except I just realized the tracking isn't in the Shipment version on CPAN. This is all my mistake, I know. But if by chance this is ready for primetime, and it's exclusion was an oversight, I thought I'd mention it.

It's great functionality, and if you need help getting it ready for CPAN, I'm happy to help!

**Comment by pullingshots** [comment]
Thanks @evanernest for pushing on this.

It's now released under version 3.01 on CPAN!
